road86/bahis-dash

- pages/ULO.py
Several topics where addressed to improve user experiences:
- added error message, when selected upazila contains no data
- adjusted y and x axis to keep their range
- date range values are always shown. Three months are shown simultaneously and only one date needs to be selected.
- clearing geolocations for higher level consistently removes lower level (no memory of old setting)
- removed separation to have lines and dots and bars depending on date range. Everything is now in bars to keep the view calmer.
Tried to test the performance by checking with different selections. No error so far was raised.
closes #74 and #75  and #53 and might have solved #63 a second time, so merging is necessary …
> fix: ulo.py error when loaded data is empty #74

- pages/Reports.py
- pages/dls.py
- pages/home.py
Please include a summary of the change(s).
You should also include motivation (why did this change required?) and which issue this pull request fixes (what problem does it solve?).
closes #87 #88 #89 #91 #97 #100 #102 #103
> fix: Fixes and completeness test

- pages/dls.py
Please include a summary of the change(s).
You should also include motivation (why did this change required?) and which issue this pull request fixes (what problem does it solve?).
closes #106 
closes #105 
closes #98 
Has the pipfile.lock or yarn.lock been updated?
No
> fix: Fixes for selection of diseases

- pages/dls.py
- deleted the Geodyntable tab
- all data till 2019 is now accessible, which also fixes the problem with the monthly comparison
- fixed some bugs I encountered while working on this.
- adds the timestamp of the patient datafile
Please include a summary of the change(s).
You should also include motivation (why did this change required?) and which issue this pull request fixes (what problem does it solve?).
closes #109
closes #101 
closes #67 
- [x …
> fix: delete geodyntable, make all data accessible (and makes the monthy comparison work,  fix bugs, adds the timestamp of the patient datafile

- components/navbar.py
- pages/dls.py
correct last PR, which lacked these features, because they got lost while trying.
Date of datafile modification added in the navbar.
Output of toal reports adjusted for x-position
Please include a summary of the change(s).
You should also include motivation (why did this change required?) and which issue this pull request fixes (what problem does it solve?).
- [x ] I have …
> fix: print date of database and position of total numbers

- components/navbar.py
* fix: print date of database and position of total numbers
correct last PR, which lacked these features deleted accidently.
* update shifting the position slightly
> fix: print date of database and position of total numbers (#114)

- pages/dls.py
This fix removes "Date" from the x-axis label
closes #122
> fix: x-axis label removed

- .flake8
- .github/workflows/lint-and-format.yml
- Pipfile
- Pipfile.lock
- README.md
- app.py
- components/navbar.py
- pages/Reports.py
- pages/ULO.py
- pages/dls.py
- pages/home.py
- pyproject.toml
As it says on the tin. By adding (and using) these tools we can build more consistent code across multiple coders.
Easiest was is to run `pipenv run black .` and `pipenv run flake8 .` from the root of the repository. You could also enable and configure the appropriate extensions in your IDE. Finally, on PRs both flake8 and black will be run automatically - right now these are not _required_ for a merge to `main`, but they will be eventually.
@yokat currently there are three errors I can't solve:
```bash
./pages/Reports.py:148:1: C901 'generate_reports_heatmap' is too complex (49)
./pages/dls.py:447:121: E501 line too long (169 > 120 characters)
./pages/dls.py:542:1: C901 'update_whatever' is too complex (22)
```
The "line too long" error is actually related to one of the other errors so, …
> feat: add black formatter and flake8 linter

- pages/dls.py
The total number of reports was wrongly calculated in the reports tab. This PR fixes the problem
closes #159
- [ x] I have assigned at least one reviewer.
> fix: total numbers in reports showed false

- components/ReportsSickDead.py
- pages/dls.py
Separates Reports into two: Large Animal and Poultry.
relates road86/repository_name#118
> feat:  poultry and la separation

- pages/dls.py
because there can now be only one disease, some checks need to be updated:
closes #163 163
> fix: error because disease can only be one entry

- components/yearly_comparison.py
- pages/dls.py
yearly comparison is now connected with diseases. some linter format changes and some unnecessary lines deleted
closes #140 
> fix: connect yearly comparison with diseases

- components/fetchdata.py
- components/pathnames.py
- pages/dls.py
Some first steps to refactor (change the internal structure for better readiblity and usabilty : Moved out the pathnames settings and setup a file to fetch data, where all data request are bundled.
Modified dls.py to accommodate the changes
> feat: refactoring, separated pathnames and fetchdata

- components/CompletenessReport.py
- pages/dls.py
link not clean. fixed to correct file link
> fix: link bug

- components/CompletenessReport.py
changed completenesscolor replaced green with white for better visibility.
> fix: completeness color adjusted to white

- components/CompletenessReport.py
- pages/dls.py
fixed tooltip: Reports and no upazila name. fixed also artificially negative case numbers, which were a temporary solution to visualize non-responders. Added legend to the map
closes #147 
closes #127 
> fix: hovertip and numbers on map

- components/ReportsSickDead.py
- pages/dls.py
include a slider for demo purposes
changed colors of reports
closes #85
closes #129
> fix: Slider merged to latest version

- pages/dls.py
changed landing page to dls
closes #178
> fix: changed home to dls page

- components/CompletenessReport.py
- pages/dls.py
non-responders are now shown in completeness map
bug when switching immediately to division, while being on district is fixed
closes #170
closes #180
Have any database changes been committed as part of this pull request?
> fix: completeness non responders

- pages/dls.py
fixed order of filtering to prevent false updates of the date subset to 
https://github.com/road86/bahis-data/issues/30
List any dependencies that have been removed/added/changed in this pull request.
Has the pipfile.lock or yarn.lock been updated?
Please describe the new tests that have been added for this change along with any additional instructions required to reproduce a successful test and/or a list of any relevant details for your test configuration.
Please describe the new documentation that has been added for this change (is there new user documentation? is there new developer documentation? is the developer documentation …
> fix: date subset

- Pipfile
added package dash mantine to access an easier date range picker
closes #191
hope it does it's work
> build: added module mantine to dependencies

- components/navbar.py
- pages/Remaining.py
Added report for remaining animals, which are neither poultry nor large animals.
closes #176 
closes #183 
> fix: Added Remaining non poultry and non-large animals report

- components/navbar.py
- pages/TopTen.py
- pages/YearlyComparison.py
- pages/Zoonotic.py
- pages/ZoonoticTrend.py
Added the possibility to see the development of the Top 10 diseases.
Also included text to mark that years in yearly comparison can be selected and de-selected.
closes #188
closes #202
closes #123 
the latter by stupidity, because I forgot to switch the branch
> feat: Zoonotic Disease Development (not Trend)

- app.py
relates road86/repository_name#123
- [ x] I have assigned at least one reviewer.
> fix: minor textual change referring to #123

- components/DateRangeSelect.py
- components/navbar.py
- pages/Completeness.py
- pages/RegionalDyn.py
- pages/home.py
- pages/not_found_404.py
improved visualisation of reports over time
> feat: Further improvements

- components/navbar.py
- pages/home.py
> fix: homepagelink

- app.py
- components/MapNResolution.py
- components/RegionSelect.py
fixed mechanism for georesolution selection, which created a bug
closes #207
> fix: bug with hovering and geores selection 

- app.py
farm assessment has no diagnosis entry, thus can't be filtered by.
closes  #219
> fix: diagnosis bug

- components/navbar.py
in the menu, sink surveillance and AMR is not needed at the moment so they need to be taken out in order to not confuse people.
closes #221
> fix: remove sink surveillance and AMR option

- app.py
- components/ReportsSickDead.py
- components/navbar.py
- pages/Export.py
- pages/TopTen.py
Start of changes.
sidemenu order, export column numbers, export menu item, diseaselist, number of reports instead of counts in topten
closes #238 
closes #239
closes #243 
closes #223 
closes #235  
> feat: Features and mods day1

- app.py
- pages/BsEntrance.py
- pages/BsEquipment.py
- pages/BsPersonell.py
- pages/BsProduction.py
- pages/Completeness.py
- pages/LargeAnimal.py
- pages/Poultry.py
- pages/RegionalDyn.py
- pages/RegionalStats.py
- pages/Remaining.py
- pages/TopTen.py
- pages/YearlyComparison.py
- pages/Zoonotic.py
- pages/home.py
small one, yaxis setting for farm assessment, and figure titles bold
closes #248 
closes #250 
> feat: #250 yaxis label, farm, #248 chart title center

- app.py
- components/ReportsSickDead.py
- pages/Completeness.py
- pages/TopTen.py
Infrastructure: general simplify and copy error in top10, ticks in changing time range in reports, prevent dropping down graphs
closes #232
closes #234 
closes #237
closes #252 
closes #253
> feat: Features and mods day 4

- app.py
- components/DateRangeSelect.py
- components/DiseaseSelect.py
- components/MapNResolution.py
- components/RegionSelect.py
- components/ReportsSickDead.py
- components/fetchdata.py
- components/navbar.py
- pages/ExportFA.py
- pages/ExportPR.py
- pages/FAABAware.py
- pages/FAABClass.py
- pages/FAABUsage.py
- pages/FABsEntrance.py
- pages/FABsEquipment.py
- pages/FABsPersonell.py
- pages/FABsProduction.py
- pages/FormSummary.py
- pages/PRCompleteness.py
- pages/PRLargeAnimal.py
- pages/PRPoultry.py
- pages/PRRegionalDyn.py
- pages/PRRegionalStats.py
- pages/PRRemaining.py
- pages/PRTopTen.py
- pages/PRYearlyComparison.py
- pages/PRYearlyPerc.py
- pages/PRZoonotic.py
- pages/home.py
bugfixes
closes #295
closes #293
closes #291
closes #290
closes #289
closes #288
closes #287
closes #286
closes #285
closes #283
> fix: bug  url code

- components/fetchdata.py
remove print statements 
closes #296 
> fix: cleaning some prints

- app.py
- components/DateRangeSelect.py
date picker had to fulfill two functions:
- separate selection of dates
- quick change of years
closes #306 
> fix: #306 revert to datepickersingle

- pages/FAABUsage.py
- test.py
Change axis labels and show relative values in antibiotics usage
closes  #308
> feat: Taifur requests

- components/DateRangeSelect.py
- components/ReportsSickDead.py
- components/SpeciesSelect.py
- components/fetchdata.py
- components/navbar.py
- pages/FOverallFarmdataRep.py
- pages/FormSummary.py
- pages/PRLargeAnimal.py
- pages/PROverallDataRep.py
- pages/PRSpeciesWise.py
- pages/PRTopTen.py
- pages/PRZoonotic.py
- pages/home.py
fixes graphs with missing values if only one value, from and to dates closer with no padding, zoonotic disease incidence fixed y axis, rename regional stats to overall data, TOP10 without "k", Species report, farm assessment in form summary, farm assessment also in home, regional overall data also for farm assessment
closes #310 
closes #311 
closes #312 
closes #313 
closes #314 
closes #315 
closes #316 
closes #317 
closes #318 
closes #319 
> feat: Dls change requests part 1

- components/DateRangeSelect.py
- pages/PRTopTen.py
- pages/home.py
change appearance in home, Top10 and date select
closes #333 
closes #334  
closes #335 
> feat: Further change requests 2

- app.py
- pages/FAOverallFarmdataRep.py
- pages/PRCompleteness.py
- pages/PROverallDataRep.py
reload of farm assessment report possible,
show information when no data
reports in overall farm data without decimals
closes #341 
closes #342 
closes #343 
closes #344 
closes #345 
> feat: Further change requests 4

- app.py
- components/fetchdata.py
- pages/PRCompleteness.py
- pages/home.py
update of all indicator numbers, title adjustments of indicators, export of completeness table.
closes #347 
closes #348
closes #349
> feat: Features and fixes

- pages/PRCompleteness.py
made hover information in completeness consistently number of reports, 
added descriptive text to completeness
caught error if empty
sorted values alphabetically
closes #355 
closes #356  
closes #357  
closes #358  
closes #359 
List any dependencies that have been removed/added/changed in this pull request.
Has the pipfile.lock or yarn.lock been updated?
Please describe the new tests that have been added for this change along with any additional instructions required to reproduce a successful test and/or a list of any relevant details for your test configuration.
Please describe the new documentation that has been added for this change (is there new …
> feat: Feat n fixes
